name: Unit Tests
run-name: Unit tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  backend-unit-tests:
    name: Back-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run unit tests
        run: mvn -B test --file pom.xml jacoco:report
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: Jacoco Reports
          path: back/target/site/jacoco/
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar


  frontend-unit-tests:
    name: Front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - name: Upload Karma report
        uses: actions/upload-artifact@v4
        with:
          name: Karma Reports
          path: front/coverage/bobapp
      - name: install scanner
        run: npm install -g sonarqube-scanner
      - name: run sonar scanner
        run: sonar-scanner -Dsonar.token=${{secrets.SONAR_TOKEN}}

  dockerize-backend:
    name: Build & Push Back-end Docker Image
    runs-on: ubuntu-latest
    needs: [backend-unit-tests, frontend-unit-tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Back-end image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest ./back
      - name: Push Back-end image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest

  dockerize-frontend:
    name: Build & Push Front-end Docker Image
    runs-on: ubuntu-latest
    needs: [backend-unit-tests, frontend-unit-tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Front-end image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest ./front
      - name: Push Front-end image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
